accounts/urls.py
from django.urls import path, include

from accounts.views import ActivateAccountView, SignUpGenericView

app_name = "accounts"

urlpatterns = [
    path("signup/", SignUpGenericView.as_view(), name="signup"),
    path("activate/<uidb64>/<token>/", ActivateAccountView.as_view(), name="activate"),
    path("", include("django.contrib.auth.urls")),
]

task/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls

from task.views import index, TaskTypeListView, PositionListView, TaskTypeUpdateView, TaskTypeDetailView, \
    TaskTypeDeleteView, TaskTypeCreateView, PositionDetailView, PositionUpdateView, PositionDeleteView, \
    PositionCreateView, WorkerListView, WorkerCreateView, WorkerUpdateView, WorkerDetailView, WorkerDeleteView, \
    TaskListView, TaskDetailView, TaskCreateView, TaskUpdateView, TaskDeleteView, TaskCompleteStatusView


app_name = "task"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name="home"),
    path("tasktypes/",
         TaskTypeListView.as_view(),
         name="taskType-list"
         ),
    path("tasktypes/<int:pk>/detail/",
         TaskTypeDetailView.as_view(),
         name="taskType-detail"
         ),
    path("tasktypes/create/",
         TaskTypeCreateView.as_view(),
         name="taskType-create"
         ),
    path("tasktypes/<int:pk>/update/",
         TaskTypeUpdateView.as_view(),
         name="taskType-update"
         ),
    path("tasktypes/<int:pk>/delete/",
         TaskTypeDeleteView.as_view(),
         name="taskType-delete"
         ),
    path("position/",
         PositionListView.as_view(),
         name="position-list"
         ),
    path("positions/create/",
         PositionCreateView.as_view(),
         name="position-create"
         ),
    path("positions/<int:pk>/detail/",
         PositionDetailView.as_view(),
         name="position-detail"
         ),
    path("positions/<int:pk>/update/",
         PositionUpdateView.as_view(),
         name="position-update"
         ),
    path("positions/<int:pk>/delete/",
         PositionDeleteView.as_view(),
         name="position-delete"
         ),
    path("workers/",
         WorkerListView.as_view(),
         name="worker-list"
         ),
    path("workers/create/",
         WorkerCreateView.as_view(),
         name="worker-create"
         ),
    path("workers/<int:pk>/update/",
         WorkerUpdateView.as_view(),
         name="worker-update"
         ),
    path("workers/<int:pk>/detail/",
         WorkerDetailView.as_view(),
         name="worker-detail"
         ),
    path("workers/<int:pk>/delete/",
         WorkerDeleteView.as_view(),
         name="worker-delete"
         ),
    path("tasks/",
         TaskListView.as_view(),
         name="task-list"
         ),
    path("tasks/<int:pk>/detail/",
         TaskDetailView.as_view(),
         name="task-detail"
         ),
    path("tasks/create/",
         TaskCreateView.as_view(),
         name="task-create"
         ),
    path("tasks/<int:pk>/update/",
         TaskUpdateView.as_view(),
         name="task-update"
         ),
    path("tasks/<int:pk>/delete/",
         TaskDeleteView.as_view(),
         name="task-delete"
         ),
    path("tasks/<int:pk>/complete/",
         TaskCompleteStatusView.as_view(),
         name="task-complete"
         )


] + debug_toolbar_urls()

task_services/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("task.urls", namespace="task")),
    path("accounts/", include("accounts.urls")),
] + debug_toolbar_urls() + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/header.html
<header class="d-flex justify-content-between align-items-center py-3 px-5">
  <p class="display-4">Task Manager</p>
  <div id="burger-menu">
    <span></span>
  </div>

</header>

<div id="menu">
  <ul>
    {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link active text-light" href="{{ user.get_absolute_url }}">
          <i class="bi bi-person-circle"></i> User: {{ user.get_username }}
        </a>
      </li>
      <li class="nav-item">
        <form action="{% url 'accounts:logout' %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger w-100">
{#            <i class="bi bi-box-arrow-right"></i> Logout#}
            <a href="{% url 'accounts:login' %}">Logout</a>
          </button>
        </form>
      </li>
    {% else %}
      <li><a class="nav-link btn btn-primary w-100 text-light" href="{% url 'accounts:login' %}">Login</a></li>
      <li><a class="nav-link btn btn-primary w-100 text-light" href="{% url 'accounts:signup' %}">Sign Up</a></li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link text-light" href="{% url 'task:home' %}">
        <i class="bi bi-house-door"></i> Home
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link text-light" href="{% url 'task:position-list' %}">
        <i class="bi bi-briefcase"></i> All Positions
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link text-light" href="{% url 'task:taskType-list' %}">
        <i class="bi bi-tags"></i> All Task Types
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link text-light" href="{% url 'task:worker-list' %}">
        <i class="bi bi-people"></i> All Workers
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link text-light" href="{% url 'task:task-list' %}">
        <i class="bi bi-check2-square"></i> All Tasks
      </a>
    </li>
  </ul>
</div>

<script>
    var burgerMenu = document.getElementById('burger-menu');
    var overlay = document.getElementById('menu');
    burgerMenu.addEventListener('click', function () {
        this.classList.toggle("close");
        overlay.classList.toggle("overlay");
    });
</script>

templates/includes/pagination.html
{% load query_transform %}
{% if page_obj %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<div id="burger-menu">
  <div id="menu">
    <div class="text-center py-3">
      <h3 class="text-light">Task Manager</h3>
    </div>
    <ul class="nav flex-column">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active text-light" href="{{ user.get_absolute_url }}">
            <i class="bi bi-person-circle"></i> User: {{ user.get_username }}
          </a>
        </li>
        <li class="nav-item">
          <form action="{% url 'accounts:logout' %}" method="post" class="nav-link">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger w-100">
              <i class="bi bi-box-arrow-right"></i> Logout
            </button>
          </form>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link btn btn-primary w-100 text-light" href="{% url 'accounts:login' %}">
            <i class="bi bi-box-arrow-in-right"></i> Login
          </a>
          <a class="nav-link btn btn-primary w-100 text-light" href="{% url 'accounts:signup' %}">
            <i class="bi bi-box-arrow-in-right"></i> SignUp
          </a>
        </li>
      {% endif %}

      <hr class="text-light">
      <li class="nav-item">
        <a class="nav-link text-light" href="{% url 'task:home' %}">
          <i class="bi bi-house-door"></i> Home
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light" href="{% url 'task:position-list' %}">
          <i class="bi bi-briefcase"></i> All Positions
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light" href="{% url 'task:taskType-list' %}">
          <i class="bi bi-tags"></i> All Task Types
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light" href="{% url 'task:worker-list' %}">
          <i class="bi bi-people"></i> All Workers
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light" href="{% url 'task:task-list' %}">
          <i class="bi bi-check2-square"></i> All Tasks
        </a>
      </li>
    </ul>
  </div>
</div>